### ISSUE TITLE
Release v0.4

### ISSUE THREAD

**Issue by tkluck** [tkluck/GaloisFields.jl#2]
I'd like to release v0.4, which drops support for non-x86 architectures. This allows using dedicated instructions for characteristic-2 fields: https://github.com/tkluck/GaloisFields.jl/blob/master/src/BinaryFields.jl#L82

Another feature of v0.4 is that broadcasting now merges the ring operations (+,-,*,/) in the sense that it only does a single `mod` operation after applying those operations. There's some careful bookkeeping that avoids integer overflows.

@b-reinke , since you contributed to this package: is dropping x86 a problem for you? If so, let me know and we'll work around it. More generally, if you have any other comments about whether this package satisfies your needs, do let me know! Also if you decided to replace it by something else.

Thanks!

**Comment by b-reinke** [comment]
Dropping x86 is not an issue for me. The package mostly satisfies my needs, but at some point I wanted to some linear algebra over finite fields, such as computing the characteristic polynomial of a matrix. I am not sure what a good interface would be for the eigenvalue decomposition, as one might need to consider field extensions to give all eigenvalues.
My solution was to export the matrix to pari but an in-house solution would be nice.
