### ISSUE TITLE
Display confusion between PrimeField and BinaryField

### ISSUE THREAD

**Issue by Keno** [tkluck/GaloisFields.jl#5]
I'm not sure if this is intended or a bug, but either way it's confusing.
```
julia> @GaloisField ℤ/256ℤ
𝔽₂₅₆

julia> @GaloisField 𝔽₂₅₆
(𝔽₂₅₆, ##423)
```

The former `𝔽₂₅₆` is a `PrimeField` (even though 256 isn't prime?) while the latter is a `BinaryField`. They print the same, but behave completely differently.

**Comment by tkluck** [comment]
Thanks for flagging. I've been hesitant to add `isprime` assertions in the constructors, but after timing this I don't see a reason:

```
julia> @btime isprime($(prevprime(typemax(Int128))))
  68.619 μs (4 allocations: 2.49 KiB)
true
```
That would then throw an error in your first example. Would that solve your confusion?

**Comment by Keno** [comment]
It would solve my confusion, though of course `ℤ/256ℤ` is sometimes quite useful, so perhaps we should just add a `ModP` datatype to support things of that form that aren't finite fields and just make it work. Perhaps this isn't the correct package for that, but I figure `PrimeField` has all the code to support ModP anyway.

**Comment by tkluck** [comment]
> of course ℤ/256ℤ is sometimes quite useful, so perhaps we should just add a ModP datatype to support things of that form that aren't finite fields and just make it work.

I agree that it might be useful, but it immediately asks for new methods and functionality (chinese remainder theorem, is_zero_divisor, ideals, etc). So yep, probably not the right package.

I'll leave the issue open until I added `isprime` to the constructor.
