### ISSUE TITLE
Any plans on supporting creation finite fields over finite fields?

### ISSUE THREAD

**Issue by kirtsar** [tkluck/GaloisFields.jl#7]
It is not so rare in (for instance) coding theory to have the "tower" of Galois fields, that is, we theat code as linear subspace over GF(q^m), where q = p^n for some prime n. I understand that this thing is isomorphic to some GF(p^mn), but it could be more handy to treat it as GF(q^m).

**Comment by tkluck** [comment]
At least some support already exists, see this test set here:

https://github.com/tkluck/GaloisFields.jl/blob/a87798dd373f042656cc2b691734dc7bb388bdc7/test/arithmetic.jl#L131

Does that cover your needs, or is anything specific you are missing?

**Comment by kirtsar** [comment]
@tkluck 
Thanks, this is exactly what I want! I should have looked at tests in the first place...

**Comment by tkluck** [comment]
Excellent! As a favour, if you have time, want to submit an update to the `README` that would have helped you? I think github lets you do it in a web interface: https://github.com/tkluck/GaloisFields.jl/edit/master/README.md

I'm closing this issue now.
