### ISSUE TITLE
Nested extension continued

### ISSUE THREAD

**Issue by kirtsar** [tkluck/GaloisFields.jl#8]
1. There are no checks that the minimal polynomial is irreducible. Is it intended?
```julia
F2 = @GaloisField 2
F4 = @GaloisField! F2 x^2
@show x^(-1)
```

2. Not possible to use coefficients from field in irreducible polynomial in macro?
```julia
F2 = @GaloisField 2
F4 = @GaloisField! F2 x^2 + x + 1
# t^3 + x is irreducible over F4
@GaloisField! F4 t^3 - x
# ERROR: LoadError: Polynomials must have same variable
# However, the straight construction works well:
F64 = GaloisField(F4, :t => [1, 0, 0, x])
```

**Comment by tkluck** [comment]
Both are very reasonable feature requests. I'll separate the issues if you don't mind.

**Comment by tkluck** [comment]
Closing this issue just for bookkeeping. Feel free to open (separate) issues for any other feature requests / bugs.
